version: '3.8'

services:
  web:
    build: .
    command: >
      sh -c "
      python wb_products/manage.py makemigrations &&
      python wb_products/manage.py migrate &&
      python wb_products/manage.py runserver 0.0.0.0:8000
      "
    env_file: .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  db:
    image: postgres:16
    env_file: .env
    environment:
      POSTGRES_DB: ${DB_NAME} 
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7.4.0
    env_file: .env
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"

  celery:
    build: .
    command: celery -A wb_products worker --loglevel=info
    volumes:
      - .:/app
    working_dir: /app/wb_products
    depends_on:
      - web
      - redis

volumes:
  pgdata:
